---
- name: Build rpm of Apache httpd
  hosts: all
  become: true

  roles:
    - name: setup
      tags: setup
    - name: apr
      tags: apr
    - name: apr-util
      tags: apr-util
    - name: distcache
      tags: distcache
    - name: apache
      tags: apache
...
