---
- name: main / Download sources
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - url: "https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/18/Everything/source/SRPMS/d/distcache-1.4.5-23.src.rpm"
      dest: "{{ work_dir }}"

- name: main / Build distcache package
  become: no
  command: rpmbuild --rebuild --clean {{ work_dir }}/distcache-1.4.5-23.src.rpm
  args:
    creates: /home/vagrant/rpmbuild/RPMS/x86_64/distcache-1.4.5-23.x86_64.rpm

- name: main / Install distcache package
  yum:
    name: "{{ item }}"
  when: ansible_os_family == 'RedHat'
  with_items:
    - "/home/vagrant/rpmbuild/RPMS/x86_64/distcache-1.4.5-23.x86_64.rpm"
    - "/home/vagrant/rpmbuild/RPMS/x86_64/distcache-devel-1.4.5-23.x86_64.rpm"

- name: main / Copy packages
  command: cp -r /home/vagrant/rpmbuild /vagrant
...
