---
- name: main / Download sources
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - url: "http://archive.apache.org/dist/httpd/httpd-2.4.25.tar.bz2"
      dest: "/tmp"

- name: main / Build Apache package
  become: no
  command: rpmbuild -tb --clean --define="__check_files %{nil}" /tmp/httpd-2.4.25.tar.bz2
  args:
    creates: /home/vagrant/rpmbuild/RPMS/x86_64/httpd-2.4.25-1.x86_64.rpm

- name: main / Copy packages
  command: cp -r /home/vagrant/rpmbuild /vagrant
...
