---
- name: main / Install epel repository
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "epel-release"
  when: ansible_os_family == 'RedHat'

- name: main / Install rpmbuild
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "rpm-build"
    - "rpmdevtools"
    - "autoconf"
    - "libtool"
    - "doxygen"
    - "freetds-devel"
    - "expat-devel"
    - "libuuid-devel"
    - "db4-devel"
    - "postgresql-devel"
    - "mysql-devel"
    - "unixODBC-devel"
    - "openldap-devel"
    - "nss-devel"
    - "mailcap"
    - "pcre-devel"
    - "lua-devel"
    - "libxml2-devel"
  when: ansible_os_family == 'RedHat'

- name: main / Setup rpmbuild tree
  become: no
  command: rpmdev-setuptree
  args:
    creates: /home/vagrant/.rpmmacros

- name: main / Download sources
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - url: "http://archive.apache.org/dist/apr/apr-1.5.2.tar.bz2"
      dest: "/tmp"
    - url: "http://archive.apache.org/dist/apr/apr-util-1.5.4.tar.bz2"
      dest: "/tmp"
    - url: "https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/18/Everything/source/SRPMS/d/distcache-1.4.5-23.src.rpm"
      dest: "/tmp"
    - url: "http://archive.apache.org/dist/httpd/httpd-2.4.25.tar.bz2"
      dest: "/tmp"

- name: main / Build apr package
  become: no
  command: rpmbuild -tb --clean /tmp/apr-1.5.2.tar.bz2
  args:
    creates: /home/vagrant/rpmbuild/RPMS/x86_64/apr-1.5.2-1.x86_64.rpm

- name: main / Install apr package
  yum:
    name: "{{ item }}"
  when: ansible_os_family == 'RedHat'
  with_items:
    - "/home/vagrant/rpmbuild/RPMS/x86_64/apr-1.5.2-1.x86_64.rpm"
    - "/home/vagrant/rpmbuild/RPMS/x86_64/apr-devel-1.5.2-1.x86_64.rpm"

- name: main / Build apr-util package
  become: no
  command: rpmbuild -tb --clean /tmp/apr-util-1.5.4.tar.bz2
  args:
    creates: /home/vagrant/rpmbuild/RPMS/x86_64/apr-util-1.5.4-1.x86_64.rpm

- name: main / Install apr-util package
  yum:
    name: "{{ item }}"
  when: ansible_os_family == 'RedHat'
  with_items:
    - "/home/vagrant/rpmbuild/RPMS/x86_64/apr-util-1.5.4-1.x86_64.rpm"
    - "/home/vagrant/rpmbuild/RPMS/x86_64/apr-util-devel-1.5.4-1.x86_64.rpm"

- name: main / Build distcache package
  become: no
  command: rpmbuild --rebuild --clean /tmp/distcache-1.4.5-23.src.rpm
  args:
    creates: /home/vagrant/rpmbuild/RPMS/x86_64/distcache-1.4.5-23.x86_64.rpm

- name: main / Install distcache package
  yum:
    name: "{{ item }}"
  when: ansible_os_family == 'RedHat'
  with_items:
    - "/home/vagrant/rpmbuild/RPMS/x86_64/distcache-1.4.5-23.x86_64.rpm"
    - "/home/vagrant/rpmbuild/RPMS/x86_64/distcache-devel-1.4.5-23.x86_64.rpm"

- name: main / Build Apache package
  become: no
  command: rpmbuild -tb --clean --define="__check_files %{nil}" /tmp/httpd-2.4.25.tar.bz2
  args:
    creates: /home/vagrant/rpmbuild/RPMS/x86_64/httpd-2.4.25-1.x86_64.rpm

- name: main / Copy packages
  command: cp -r /home/vagrant/rpmbuild /vagrant
...
